# Generated by Django 6.0.1 on 2026-01-15 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=120)),
                ('opis', models.TextField(blank=True)),
                ('termin', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'Do zrobienia'), ('doing', 'W trakcie'), ('done', 'Zrobione')], default='todo', max_length=10)),
                ('priorytet', models.IntegerField(choices=[(1, 'Niski'), (2, 'Średni'), (3, 'Wysoki')], default=2)),
                ('utworzono', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
